use lazy_static::lazy_static;
use rand::seq::SliceRandom;

use crate::rng;

lazy_static! {
    static ref NAMES: Vec<&'static str> = vec![
        "Aaliyah",
        "Yusef",
        "Ciaran",
        "Deshawn",
        "Eilidh",
        "Haruki",
        "Isha",
        "Juniper",
        "Katlego",
        "Lior",
        "Abdulrahman",
        "Bhattacharya",
        "Cvetkovic",
        "Dmitriev",
        "Eze",
        "Fang",
        "Ghosh",
        "Hikmet",
        "Iliev",
        "Joensen",
        "Kalayci",
        "Larsson",
        "Mikhailov",
        "Nguyen",
        "O'Farrell",
        "Petrovic",
        "Qureshi",
        "Radovanovic",
        "Srinivasan",
        "Tzvetanov",
        "Ueda",
        "Volkan",
        "Wei",
        "Ximena",
        "Yoshida",
        "Zhang",
        "Anastasiou",
        "Bajrami",
        "Chen",
        "Dimitrov",
        "Evgeniev",
        "Fujimura",
        "Gupta",
        "Hansson",
        "Ikeda",
        "Johansson",
        "Kwon",
        "Li",
        "Mazumdar",
        "Nakamura",
        "Obafemi",
        "Padmaja",
        "Quirke",
        "Ragnvaldsson",
        "Sigurdsson",
        "Tendulkar",
        "Uthayakumar",
        "Vali",
        "Wanyeki",
        "Xing",
        "Yigit",
        "Zalmai",
        "Achari",
        "Beyene",
        "Chidubem",
        "Devdas",
        "Ermias",
        "Fekade",
        "Girma",
        "Habte",
        "Indira",
        "Joshi",
        "Kamau",
        "Lal",
        "Mandava",
        "Nag",
        "Oli",
        "Patil",
        "Qadir",
        "Rana",
        "Shah",
        "Tekle",
        "Uppal",
        "Varma",
        "Walia",
        "Xiao",
        "Yadav",
        "Zaidi"
    ];
}

pub fn random_name(rng: &mut rng::Rng) -> String {
    let first_name = NAMES.choose(&mut rng.inner).unwrap().to_string();
    let last_name = NAMES.choose(&mut rng.inner).unwrap().to_string();
    format!("{} {}", first_name, last_name)
}
