name: dev build
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  build:
    name: dev build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup wasm-bindgen
        uses: cargo install -f wasm-bindgen-cli
      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown
